# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=5)),
                ('damage', models.IntegerField()),
                ('affinity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weapon_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('weapon_type', models.CharField(max_length=50)),
                ('damage_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon_type'),
        ),
    ]
