# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_weapon_abbrv'),
    ]

    operations = [
        migrations.CreateModel(
            name='bow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='chargeBlade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='greatsword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='gunlance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='hammer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='heavyBowgun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='huntingHorn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='insectGlaive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='switchAxe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('raw', models.IntegerField()),
                ('element', models.IntegerField()),
                ('elementType', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusType', models.CharField(max_length=30)),
                ('affinity', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
    ]
